wandb_version: 1

batch_size:
  value: 64
dim:
  value: 100
dropout_rate:
  value: 0.2
hidden_units:
  value: 32
lr:
  value: 0.001
lstm_layers:
  value: 1
max_len:
  value: 50
recurrent_dropout_rate:
  value: 0.2
