wandb_version: 1

? "\n        'max_len': {\n            'values': [50]\n        },batch_size"
: desc: null
  value: 128
dim:
  desc: null
  value: 100
_wandb:
  desc: null
  value:
    python_version: 3.11.4
    cli_version: 0.15.12
    framework: keras
    is_jupyter_run: false
    is_kaggle_kernel: false
    start_time: 1702716878.448278
    t:
      1:
      - 2
      - 3
      - 5
      - 53
      - 55
      2:
      - 2
      - 3
      - 5
      - 53
      - 55
      3:
      - 2
      - 23
      - 37
      4: 3.11.4
      5: 0.15.12
      8:
      - 3
      - 5
      13: windows-amd64
